FROM openjdk:19
COPY . /project2boot/src/main
WORKDIR /project2boot/src/main
RUN javac src/main/java/ua/donetc/project2boot/Project2bootApplication.java
CMD ["java", "ua.donetc.project2boot.Project2bootApplication"]
